version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: babich-postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432" #"ХОСТ:КОНТЕЙНЕР" Левый 5432 (хост) — порт на вашем компьютере, который будет открыт, Правый 5432 (контейнер) — порт внутри контейнера PostgreSQL, который слушает
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: babich-nginx
    ports:
      - "80:80"
    volumes:
      # TODO: В продакшене заменить на Dockerfile с COPY
      # Сейчас :ro убран для разработки, чтобы можно было копировать файлы
      # План: создать Dockerfile.nginx и использовать build вместо volume
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # platform host
      - ./platform-ui/dist/platform/browser:/usr/share/nginx/platform
      # babich-chat-ui
      - ./platform-ui/dist/babich-chat-ui/browser:/usr/share/nginx/chat
      # Для продакшена использовать:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./babich-chat-ui/dist/babich-chat-ui/browser:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  postgres_data: